### ISSUE TITLE
I don't think you can make this public legally.

### ISSUE THREAD

**Issue by hiteshjoshi** [bketelsen/spotlight#3]
Just stumbled upon while browsing. It would be best if you did not make this public, this is against the terms and conditions at tailwindui.com

Here are the terms. https://tailwindui.com/license

PS: I don't work for them. I am a user like you.

**Comment by kothavade** [comment]
@hiteshjoshi see https://github.com/bketelsen/spotlight/issues/2#issuecomment-1769041693

**Comment by hiteshjoshi** [comment]
Read it, But you should read this clearly. https://tailwindui.com/license

---
Examples of usage not allowed by the license:

    Creating a repository of your favorite Tailwind UI components or templates (or derivatives based on Tailwind UI components or templates) and publishing it publicly.

**Comment by hiteshjoshi** [comment]
Here is what chatGPT has to say.

<img width="563" alt="Screenshot 2023-11-30 at 12 22 43 PM" src="https://github.com/bketelsen/spotlight/assets/217911/3e98f4dc-f965-4b8d-8ba7-63aaa3faa299">

**Comment by Cristuker** [comment]
It's public, but we can't use this code, right?

**Comment by hiteshjoshi** [comment]
whatever
